### ISSUE TITLE
Status of ToDos in README?

### ISSUE THREAD

**Issue by JoeMurray** [aghstrategies/com.aghstrategies.airmail#12]
I'm wondering if the README is a bit of out date as it seems to imply the code is not yet handing opens, click-throughs, etc, not unsubscribing complaints. Or are these still outstanding tasks for some or all of the integrations?

**Comment by alifrumin** [comment]
Good question. I think these todos are more confusing than helpful and im going to delete them.

**Comment by alifrumin** [comment]
Deleted with this commit: https://github.com/aghstrategies/com.aghstrategies.airmail/commit/315d6f5ff31f70ea022ac3b42ebaed13408569d5
