### ISSUE TITLE
Using SendGrid, configuration save still requires Elastic Email unsubscribe link

### ISSUE THREAD

**Issue by bph** [aghstrategies/com.aghstrategies.airmail#15]
"Please correct the following errors in the form fields below: Elastic Email unsubscribe link is a required field."

![Screen Shot 2021-02-04 at 11 47 06 AM](https://user-images.githubusercontent.com/39980/106926333-fc80bb80-66de-11eb-8d39-93067415ddc9.png)

**Comment by alifrumin** [comment]
Thanks @bph! This should now be resolved by https://github.com/aghstrategies/com.aghstrategies.airmail/pull/16
