### ISSUE TITLE
Status of this project vs lab.civicrm.org/extensions/sendgrid

### ISSUE THREAD

**Issue by twomice** [aghstrategies/com.aghstrategies.airmail#19]
The README at https://lab.civicrm.org/extensions/sendgrid starts with "Please consider using https://github.com/aghstrategies/com.aghstrategies.airmail as it is more recent." (this line added by @joemurray)

Do the airmail developers view this project as a complete replacement the sendgrid extension? I see this extension is meant to support multiple services, which is a convenience to CiviCRM consultants; beyond that, are you aware of any particular reasons to pick one extension over the other?

**Comment by elisseck** [comment]
I guess this question got overlooked!

I am not aware of a reason to use one extension over the other, but for what it's worth we use this one currently and it works well for event handling.

I am also not aware of a reason to use both extensions, so I suppose in that sense yes it is a replacement.

**Comment by twomice** [comment]
Thanks @elisseck !
