### ISSUE TITLE
EventActions functions missing static declaration

### ISSUE THREAD

**Issue by rbaugh** [aghstrategies/com.aghstrategies.airmail#29]
The [open](https://github.com/aghstrategies/com.aghstrategies.airmail/blob/master/CRM/Airmail/EventAction.php#L46) and [click](https://github.com/aghstrategies/com.aghstrategies.airmail/blob/master/CRM/Airmail/EventAction.php#L56) functions are not declared as static functions, but are being referenced as static functions in the Sendgrid webhook [processor](https://github.com/aghstrategies/com.aghstrategies.airmail/blob/master/CRM/Airmail/Backend/Sendgrid.php#L57).

This is causing a fatal error when Sendgrid is sending over the open and click actions to be logged into Civicrm.

**Comment by agh1** [comment]
thanks for pointing this out @rbaugh!
