### ISSUE TITLE
Constant undefined method logs in Drupal 8

### ISSUE THREAD

**Issue by elisseck** [aghstrategies/com.aghstrategies.airmail#4]
`Error: Call to undefined method CRM_Airmail_Utils::click() in CRM_Airmail_Backend_Sendgrid->processMessages() (line 62 of .../public_html/web/sites/default/files/civicrm/ext/com.aghstrategies.airmail/CRM/Airmail/Backend/Sendgrid.php)`

Installed with CiviCRM in D8 using Sendgrid. Bounce tracking appears to be working properly. The extension is generating these logs at a rate of ~10/minute on this site. Not 100% sure what the trigger is but I can work on a PR for it. Just logging here so I don't forget to do so.

In the meantime, any thoughts on that?

**Comment by agh1** [comment]
Whoops I think that line should be `CRM_Airmail_EventAction::click()` not Utils.

**Comment by agh1** [comment]
#5 merged, closing
