### ISSUE TITLE
Bunch of "Error: Call to undefined function _airmail_civix_civicrm_SMTH" 

### ISSUE THREAD

**Issue by yurg** [aghstrategies/com.aghstrategies.airmail#50]
There were 5 or 6 places across the code with these.  After commenting out all undefined functions the extension looks to be working.

**Comment by chrisgaraffa** [comment]
Hi @yurg, please try yesterday's 2.2.3 release and see if that's working for you.

**Comment by yurg** [comment]
@chrisgaraffa Have tried the most recent 2.2.4, looks fine so far, thank you!
